stages:
  - release
  - build
  - config

release:
  image: node:16
  stage: release
  only:
    refs:
      - master
  script:
    - touch CHANGELOG.md
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md

build acorn app:
  image: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image/releases/3.7.1-kube-1.20.11-alpine-3.14
  stage: build
  services:
    - name: registry.gitlab.com/gitlab-org/cluster-integration/test-utils/k3s-gitlab-ci/releases/v1.25.0-k3s1
      alias: k3s
  script:
    - apk add curl
    - curl -f k3s:8081 > k3s.yaml
    - export KUBECONFIG=$(pwd)/k3s.yaml
    - kubectl version
    - kubectl cluster-info
    - curl https://get.acorn.io | sh
    - acorn install
    - acorn build -t docker.io/lucj/voting:$CI_COMMIT_TAG
    - echo "acorn login..."
    - echo "acorn push..." 
  only:
    - tags

update config:
  stage: config
  image: lucj/ci:1.0
  script:
    - cd acorn
    - yq -i ".spec.image=\"docker.io/lucj/voting:${CI_COMMIT_TAG}\"" ./app.yaml
    - git add ./app.yaml   
    - git commit -m "Update app with tag $CI_COMMIT_TAG"
    - git push origin master
  only:
    - tags