stages:
  - release
  - config

release:
  image: node:16
  stage: release
  only:
    refs:
      - master
  script:
    - touch CHANGELOG.md
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md

update config:
  stage: config
  image: lucj/ci:1.0
  script:
    - cd acorn
    - yq -i ".spec.image=\"docker.io/lucj/voting:${CI_COMMIT_TAG}\"" ./app.yaml
    - git add ./app.yaml   
    - git commit -m "Update app with tag $CI_COMMIT_TAG"
    - git push origin master
  only:
    - tags