{{ if eq .Values.ingress true }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`vote.techwhale.io`)
    kind: Rule
    services:
    - name: vote-ui
      port: 5000
  - match: Host(`result.techwhale.io`)
    kind: Rule
    services:
    - name: result-ui
      port: 5001
  tls:
    certResolver: le
{{ end }}
