apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-ui
  name: result-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-ui
  template:
    metadata:
      labels:
        app: result-ui
    spec:
      containers:
        - image: {{ .Values.registry }}/result-ui:{{ index .Values "result-ui" "tag" }}
          name: result-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: result-ui