apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - image: {{ .Values.registry }}/vote:{{ .Values.vote.tag }}
          command:
          - "/bin/sh"
          - "-c"
          - "gunicorn app:app -b 0.0.0.0:5000 --log-file - --access-logfile - --workers 2 --keep-alive 0 --timeout 600"
          name: vote
          {{- if .Values.nats }} 
          env:
          - name: BACKEND
            value: {{ if eq .Values.nats "enabled" }}"nats"{{ else }}"db"{{ end }}
          {{- end }}
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 5000
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi 
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - name: temp
            mountPath: /tmp
      volumes:
      - name: temp
        emptyDir: {}

