{{- if or (not .Values.nats) (eq .Values.nats "disabled") }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: {{ .Values.registry }}/worker:{{ .Values.worker.tag }}
          name: worker
          imagePullPolicy: Always
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi 
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
{{ end }}
