---
# Source: votingapp/templates/db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:15.1-alpine3.17
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 5432
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi 
              cpu: 100m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - mountPath: /var/run/postgresql
              name: run
      volumes:
        - name: data
          emptyDir: {}
        - name: run
          emptyDir: {}
