---
# Source: votingapp/templates/result-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-ui
  name: result-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-ui
  template:
    metadata:
      labels:
        app: result-ui
    spec:
      containers:
        - image: registry.gitlab.com/voting-application/result-ui:v1.0.11
          name: result-ui
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 80
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi 
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
            #runAsUser: 10000
            #runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            #capabilities:
            #  drop:
            #  - ALL
