registry: registry.gitlab.com/voting-application
# Microservices tags
vote-ui:
  tag: v1.0.13
vote:
  tag: v1.0.7
worker:
  tag: v1.0.4
result:
  tag: v1.0.9
result-ui:
  tag: v1.0.11

# Using NATS instead of worker mode. Possible values: enabled, disabled (default)
# nats: disabled

# Ingress
#  ingress: 
#    enabled: false
#    tls: false (ignored if ingress disabled)
